version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
configuration:
  - Release
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack ./src/Snake.Core/Snake.Core.csproj
  - cmd: dotnet pack ./src/Snake.Extensions/Snake.Extensions.Autofac/Snake.Extensions.Autofac.csproj
  - cmd: dotnet pack ./src/Snake.Extensions/Snake.Extensions.Mvc/Snake.Extensions.Mvc.csproj
  - cmd: dotnet pack ./src/Snake.Extensions/Snake.Extensions.Serilog/Snake.Extensions.Serilog.csproj
  - cmd: dotnet pack ./src/Snake.Extensions/Snake.Extensions.Swagger/Snake.Extensions.Swagger.csproj
  - cmd: appveyor PushArtifact ./src/Snake.Core/bin/Release/Snake.Core.1.0.2.nupkg
  - cmd: appveyor PushArtifact ./src/Snake.Extensions/Snake.Extensions.Autofac/bin/Release/Snake.Extensions.Autofac.1.0.2.nupkg
  - cmd: appveyor PushArtifact ./src/Snake.Extensions/Snake.Extensions.Mvc/bin/Release/Snake.Extensions.Mvc.1.0.2.nupkg
  - cmd: appveyor PushArtifact ./src/Snake.Extensions/Snake.Extensions.Serilog/bin/Release/Snake.Extensions.Serilog.1.0.2.nupkg
  - cmd: appveyor PushArtifact ./src/Snake.Extensions/Snake.Extensions.Swagger/bin/Release/Snake.Extensions.Swagger.1.0.2.nupkg
clone_depth: 1
# test_script:
#   # restore packages for our unit tests
#   - cmd: dotnet restore ./tests/tests.csproj --verbosity m
#   # run the unit tests (requires changing into the test directory)
#   - cmd: cd tests
#   - cmd: dotnet xunit
# on_finish :
deploy:
  provider: NuGet
  api_key:
    secure: Pr85YtvKtnrh7tWYGq3ALBLsfUPowAmbMmBxfuSI6eQwxgDTCeqm+o5Gy8fDYj0Z
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/