version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp2.0/publish
  - cmd: dotnet publish ./src/Snake.Core/Snake.Core.csproj
  - cmd: dotnet publish ./src/Snake.Extensions/Snake.Extensions.Autofac/Snake.Extensions.Autofac.csproj
  - cmd: dotnet publish ./src/Snake.Extensions/Snake.Extensions.Mvc/Snake.Extensions.Mvc.csproj
  - cmd: dotnet publish ./src/Snake.Extensions/Snake.Extensions.Serilog/Snake.Extensions.Serilog.csproj
  - cmd: dotnet publish ./src/Snake.Extensions/Snake.Extensions.Swagger/Snake.Extensions.Swagger.csproj
# after_build:
  # For once the build has completed
artifacts:
  - path: './src/Snake.Core/bin/Debug/netstandard2.0/publish'
    name: Snake.Core
    type: Auto
  - path: './src/Snake.Extensions/Snake.Extensions.Autofac/bin/Debug/netstandard2.0/publish'
    name: Snake.Extensions.Autofac
    type: Auto
  - path: './src/Snake.Extensions/Snake.Extensions.Mvc/bin/Debug/netstandard2.0/publish'
    name: Snake.Extensions.Mvc
    type: Auto
  - path: './src/Snake.Extensions/Snake.Extensions.Serilog/bin/Debug/netstandard2.0/publish'
    name: Snake.Extensions.Serilog
    type: Auto
  - path: './src/Snake.Extensions/Snake.Extensions.Swagger/bin/Debug/netstandard2.0/publish'
    name: Snake.Extensions.Swagger
    type: Auto
clone_depth: 1
# test_script:
#   # restore packages for our unit tests
#   - cmd: dotnet restore ./tests/tests.csproj --verbosity m
#   # run the unit tests (requires changing into the test directory)
#   - cmd: cd tests
#   - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off